apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - image: restuar/golang-app:v1.0.0
          name: go-app
          env:
            - name: APP_DB_USERNAME
              value: "root"
            - name: APP_DB_PASSWORD
              value: "toor"
            - name: APP_DB_PORT
              value: "3306"
            - name: APP_DB_HOST
              value: "mysql"
            - name: APP_DB_NAME
              value: "alta"
          ports:
            - containerPort: 8080
              name: go-app
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  ports:
    - port: 8080
  selector:
    app: go-app